apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  selector:
    app: account-service
  type: NodePort
  ports:
    - port: 8081
      nodeport: 30001
  # ports:
  #   - name: port1
  #     port: 30001
  #     targetPort: 30001
  #   - name: port2
  #     port: 27017
  # type: NodePort
