apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  selector:
    app: account-service
  ports:
    - name: port1
      port: 30001
      targetPort: 30002
    - name: port2
      port: 27017
  type: NodePort
