apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - name: port1
      port: 80
    - name: port2
      port: 27017
  type: NodePort
