apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  selector:
    service: account-service
  ports:
    - name: port1
      port: 2222
      targetPort: 9376
    - name: port2
      port: 27017
  type: LoadBalancer
