apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: thegaijin/account-service
          ports:
            - containerPort: 80
        - name: mongo
          image: library/mongo:4.1.1
          ports:
            - containerPort: 27017
