apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: micro.thegaijin.xyz
      http:
        paths:
          - backend:
              serviceName: nginx-ingress
              servicePort: 18080
            path: /nginx_status
