apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: app-ingress
spec:
  rules:
    - host: micro.thegaijin.xyz
      http:
        paths:
          - path: /account
            backend:
              serviceName: account-service
              servicePort: 80
          - path: /customer
            backend:
              serviceName: customer-service
              servicePort: 3333
