apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: thegaijin/customer-service
          ports:
            - containerPort: 3333
        - name: mongo
          image: library/mongo:4.1.1
          ports:
            - containerPort: 27017
