apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - name: port1
      port: 30002
      targetPort: 30002
    - name: port2
      port: 27017
  type: NodePort
