apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    run: customer-service
spec:
  selector:
    service: customer-service
  ports:
    - name: port1
      port: 3333
    - name: port2
      port: 27017
